### ISSUE TITLE
`pydot` error for Windows pip install: `dot` executable not in path

### ISSUE THREAD

**Issue by CBroz1** [datajoint/datajoint-python#1033]
### Description

[This pydot issue](https://github.com/pydot/pydot/issues/205) summarizes the issues for Windows users. For DataJoint Windows users, `pip install datajoint` may result in the following errors when calling `dj.Diagram`:
```
FileNotFoundError: [WinError 2] "dot" not found in path.
```

### Reproducibility
Include:
- OS WIN
- Python 3.8
- DataJoint 0.13.5
- Minimum number of steps to reliably reproduce the issue
```
pip install datajoint
from any_pipeline import table
import datajoint as dj
dj.Di(table)
```

### Expected Behavior

When installing datajoint according to [instructions](https://tutorials.datajoint.io/setting-up/datajoint-python.html), `Diagram` should work across all platforms.

Possible solves: 
1. Permit pydot's optional `prog` argument ([see source](https://github.com/pydot/pydot/blob/master/src/pydot/core.py#L1648)) across all `write_X` functions when calling `dj.Diagram(table, prog='dot.exe')`
2. Catch this `FileNotFoundError` and do one or more of the following
   1. Attempt `prog` arg ourselves.
   2. Direct users to [pydot discussion](https://github.com/pydot/pydot/issues/205)
   3. Suggest conda install of pydot

**Comment by guzman-raphael** [comment]
This is because DJ Python has one system dependency outside of pure-python which is `graphviz` for drawing diagrams. Here is a similar [issue](https://github.com/datajoint/datajoint-python/issues/924) on this and where we address this in our [documentation](https://docs.datajoint.org/python/setup/02-DataJoint-Python-Windows-Install-Guide.html?highlight=graphviz#optional-step-4-install-packages-for-erd-support). That said, we'd recommend installing using [conda-forge](https://anaconda.org/conda-forge/datajoint) as this will properly install `graphviz` + pip dependencies.

```
conda install -c conda-forge datajoint
```

We'll [add](https://github.com/datajoint/datajoint-docs/issues/229) instructions for conda install in our documentation at the next opportunity.

Closing but feel free to reopen if I missed something.
