### ISSUE TITLE
Implement default hooks

### ISSUE THREAD

**Issue by fabiansinz** [datajoint/datajoint-python#122]
Default hooks would be python functions implemented by the relation to set all attributes from all the ones that are not optional. Here is an example of the intended usage

``` python
@myschema
class Reagent(dj.Manual):
    definition = """
    # some chemical used in an experiment
    ->stock_solution
    ---
    concentration=_dilute             : double # actual concentration used
    """

    @staticmethod
    def _dilute(key):
        key['concentration'] = key['stock_concentration']/10
        return key

```

Although the static method is logically the right choise, we could think about just making it a normal method as the decorator can easily be skipped over during the implementation which is a potential source for bugs (similar to the `@property` decorator for `populated_from` ).

**Comment by dimitri-yatsenko** [comment]
This is a great feature.  Default values can be provided for attributes even for manual and lookup, effectively making them partially computed.  This defeats their definition that they are populated from outside datajoint and the default values will be applied only when called from datajoint. 

The default value may contain complex computations, even using values from other tables upstream in the dependency chain. 

The `insert` method will check if any attributes are missing and will call their default method.

If all attributes have default values, then `_make_tuples` need not be implemented and `populate` calls `insert` instead of `_make_tuples`

I wonder if the default value be a full executable python expression executable within `populate`.  E.g. 
```
concentration = self._dilute(key)
```

I wonder if it makes sense to have a default callback name.  For example, if `insert` finds any of the attribute `attribute` missing, it will attempt to call the method `self._attribute(key)`

**Comment by dimitri-yatsenko** [comment]
With regard to whether to make these callbacks static, it does not make any difference.  `populate` will call `self._default_computation(key)` and it work whether it's static or not.

**Comment by dimitri-yatsenko** [comment]
Furthermore, since the default computations are called after `_make_tuples`, `_make_tuples` can pre-compute some things that are necessary for the default value computations.  This does not require any features from datajoint.  Users can just save the necessary information as properties of `self`.

**Comment by eywalker** [comment]
Per discussion, we will start by implementing a version where users can define methods in the form of `__attribute` where *attribute* is to be replaced by the attribute name for which default computation is to be provided. For example, you can provide default value computation as follows:

```python
class Treatment(dj.Imported):
definition = """  # Monitoring of subjects on specific treatment
-> Subject
report_date                      :datetime           # date of report
treatment_start_date       :datetime           # treatment start date
---
treatment_duration          :ind                    # duration of treatment in days

def __treatment_duration(self, key):
    """
    Provides default value for the treatment duration in days, estimated simply as the difference in
    treatment start date and the report date
    """
    return (key.report_date - key.treatment_start_date).total_seconds() // (60 * 60 * 24)

**Comment by dimitri-yatsenko** [comment]
we spoke of python expressions for defaults when we were going to eval the expression, which raised the question of the contents, which was not clear.  In what context should it be evaluated?  I think at this point it makes sense to treat these as SQL expressions and pass them to the SQL declaration.
