### ISSUE TITLE
__len__ on RelationalOperand and Fetch

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#139]
Currently `__len__` is implemented on `RelationalOperand`, despite the fact most of the methods that executes query of some form have been moved into `Fetch` object. Should we move `__len__` into `Fetch` as well, or should we leave this implementation as is for convenience?

**Comment by dimitri-yatsenko** [comment]
Hm...  I see the logic of your question and I think `__len__` should be implemented in `Fetch`. The same applies to `__bool__`.

Perhaps we could keep it in `Relation` too?  It's nice to have a truth value for a relation in many expressions.   The fetch object may imply that the contents of the relation are retrieved.  

Queries are performed all over the place.  Perhaps we should say that `fetch` implies retrieving the relation's contents.  So `len(relation)` still makes sense since it does not bring the contents into python.

**Comment by fabiansinz** [comment]
I also see the logic, but I agree with @dimitri-yatsenko 's definition of fetch. I wouldn't move `len` to the fetch object exclusively.

**Comment by eywalker** [comment]
I agree with you both. I've already placed a mirror implementation of `__repr__` in Fetch, and left the function `__repr__` untouched for RelationalOperand in the PR #140

**Comment by dimitri-yatsenko** [comment]
This was fixed in #140.
