### ISSUE TITLE
_repr_html_ should be placed in Fetch

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#186]
Currently `_repr_html_` is implemented in the `RelationalOperand`. This causes the fetch execution to occur when you typein the name of the RelationalOperand (and its derivatives) in IPython/Jupyter notebook. This is in disagreement with the rest of the `repr` behavior, where we only fetch and preview table content for `repr` in the `Fetch` object. Shall we move `_repr_html_` into `Fetch` and `Fetch1` to be more consistent with the rest?

**Comment by fabiansinz** [comment]
I guess we can close this issues because now both `__repr__` and `_repr_html_` cause a fetch operation. Even though this is not in agreement with the idea that only the `fetch` object should fetch data, it reduces the effort of typing `.fetch` everytime we would like to see some content of the table.

**Comment by dimitri-yatsenko** [comment]
Now `RelationalOperand` has the `preview` method.  `RelationalOperand.__repr__` calls `preview()` when not in debug mode. 

Closing.
