### ISSUE TITLE
Generate documentation

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#19]
Generate documentation forDataJoint semi-automatically from in-code documentations. Generated documentations should be hosted on datajoint-python project site.

**Comment by fabiansinz** [comment]
Documentation can now be found on http://datajoint-python.readthedocs.org/en/latest/. I haven't tested whether the github webhook runs smoothly and we might need to fix a few things along the way so that readthedocs can build the doc on their servers. So far, I made every module that readthedocs complained about a mock module (see doc/conf.py). But at least it builds the documentation I expected.  

The next step is to massively extend the documentation of the package. Do you think that should run under this issue or should we create new one and close this one?

**Comment by eywalker** [comment]
Let's create a new issue to discuss documentation and close this one.
