### ISSUE TITLE
Serializing non `ndarray` objects

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#244]
Currently BLOB field on Python side only accepts inserting `ndarrays` of simple data types. We should provide broader serialization support on the Python side.

This, however, brings up an issue of how _compatible_ we should keep Python serialization with DataJoint matlab. Namely, should we allow Python to serialize objects that cannot be deserialized in Matlab side? Equivalently, should we allow Python to serialize via serialization scheme other than `mYm`?

**Comment by aecker** [comment]
I would vote against serialization of arbitrary data types, since it kind of defeats the purpose of a relational database and almost surely causes all sorts of trouble and complexities that we'd rather not deal with. What would be a use case where serialization of complex data types would be required or convenient? 

I think serializing 'basic' data types is sufficient. 

Since this came up in the context of the discussion around storing PKs as structs in the jobs table: I don't see a simple alternative to the scheme using a struct, so maybe serialization of dicts with simple data types is a good compromise?

**Comment by fabiansinz** [comment]
We could store them as json and deserialize them in structs and dicts on the respective ends. Newer versions of MySQL support json. https://dev.mysql.com/doc/refman/5.7/en/json.html

**Comment by dimitri-yatsenko** [comment]
We should take advantage of JSON support since MySQL and other RDBMS will provide optimized searches by data in JSON fields.

We need to add support for JSON on both sides: MATLAB and Python.  We will do so with backward compatibility.  Currently, BLOB data is prefixed with "mYm" indicating mym serialization.  We will use prefix "json" for future structured blobs.  Let's phase out mym serialization.

**Comment by dimitri-yatsenko** [comment]
Although normalization is almost always a good thing, many people prefer denormalized or "schemaless" designs.  Supporting the JSON datatype provides support for both philosophies and searches by and within the JSON fields will be quite flexible too.

**Comment by dimitri-yatsenko** [comment]
I am okay with no longer supporting mym structures and storing in JSON from now on.  We will add JSON support in both languages right away.

**Comment by fabiansinz** [comment]
Before dropping mym, let's make sure we cover all cases. We should definitely be backwards-compatible as well.

**Comment by dimitri-yatsenko** [comment]
I don't know if we should implement mym serialization in Python.  Deserialization already works.  I would rather add JSON support to both.  This should be done in the format that allows MySQL JSON functionality, i.e. no compression of the json structure.

**Comment by fabiansinz** [comment]
I am not saying we should implement it. Let's just not get rid of the deserialization.

**Comment by FloFra** [comment]
I think only supporting json will artificially inflate the space required to save simple matrices.

I would therefore suggest  to also add support for a simple binary matrix format, similar to something like this:
```
<magic byte><ndim><dim0><dim1>...<dimn><data>
```
We could then have different magic bytes based on endianness, column/row major, basic data type and precision, that explains how the data has to be parsed.

**Comment by fabiansinz** [comment]
Yes, ndarrays are not supported by json. There is a library in python called `json_tricks` that gets around that by (de)serializing the array. We'd need to implement the same on the matlab side. That said, I don't think it is a good idea to store a lot of matrices in structs in the database. I also don't think we should store each longblob as a json now, but I don't think that this is what @dimitri-yatsenko had in mind.

**Comment by dimitri-yatsenko** [comment]
I think matrices will still be serialized the old way and stored in JSON fields as binary strings.

**Comment by dimitri-yatsenko** [comment]
structs and cell arrays will become json.  Numeric arrays will be serialized the old way.

**Comment by fabiansinz** [comment]
I agree with that.

**Comment by aecker** [comment]
I'd like to re-iterate my question why we need support for complex data types. We've been pretty happy so far without them. This sounds like a major change in philosophy that is accompanied by a major coding effort, so we shouldn't just do it because it sounds nice, but instead first make sure it's something that's actually needed.

**Comment by eywalker** [comment]
Whether we deicide to implement JSON support or not (discussion of that is on #245), I'm going to quickly implement BLOB support for `dict` with simple fields as @aecker suggested.

**Comment by dimitri-yatsenko** [comment]
This has been fixed for some time now.  Need to add tests and close.

**Comment by ixcat** [comment]
clarification of current remaining status:
per discussion will additionally implement support for array-of-blobs in addition to string-based dict to allow some means to store variable length 2d+ arrays (where D1 is a python array and the rest are direct N-1D numpy ndarrays)

**Comment by ixcat** [comment]
Array-of-blobs (more correctly array-of-np-array) is what was specifically suggested for extension in today's discussion - perhaps the array-vs-blob distinction is where my description fails (i have a habit of thinking of interchanging numpy structs with blobs when thinking in datajoint terms).

As I understand it, "anything else that is already supported" is also a known-not-workable situation as concerns mYm compatibility in the case of arrays-of-strings unless this is extending to become a bigger rework of serialization entirely...

**Comment by dimitri-yatsenko** [comment]
This is rolled back into #427.  Closing as duplicate.
