### ISSUE TITLE
schema syntax permits mysql-style field attributes - should it? if so, document?

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#354]
Working on an example schema I noticed that syntax as follows:

    @schema
    class Animal(dj.Manual):
        definition = '''
        animal_id: integer
        ---
        animal_desc: varchar(32) unique
        '''

Allows the 'unique' attribute and will apply it to the underlying database table. 

However, this is not documented. So:

* Should this work?
* If so, this and any other 'permitted' attribute modifiers don't seem to be documented.

**Comment by dimitri-yatsenko** [comment]
DataJoint simply passes field declarations to MySQL without parsing it to restrict the use of SQL's modifiers such as  `DEFAULT`, `NOT NULL`, and `UNIQUE`.  However, DataJoint provides its way to implement each of these features in its own way. 

In DataJoint, there are three ways to impose a unique constraint.  

1. Make it the primary key.  We have seen some designs with a surrogate primary key with autoincrement and then a separate unique index on the natural attributes.  In some cases, a better design is to use the unique fields as the primary key instead.

2. Use a  `UNIQUE INDEX (...)` line in the declaration.  This feature may not have made into to the documentation on `datajoint.io` and we should add it.  It works the same way as in SQL, however it's more general than the `UNIQUE` modifier on a field since it can be applied to any number of attributes.

3. Use the `unique` option in the foreign key.  This is documented in http://docs.datajoint.io/data-definition/Foreign-keys.html  and is scheduled to be implemented in release 0.8.1  (Issue #301).  This is the preferred way since it is consonant with the concept that DataJoint keeps the focus on entities rather than attributes.

**Comment by ixcat** [comment]
Thanks for the clarification.

I have created initial documentation patch based on this comment in f2a4ade4 in my fork of the docs repo.

**Comment by dimitri-yatsenko** [comment]
Let's close this and take it to the documentation?

**Comment by eywalker** [comment]
Agreed - let's continue this on the doc repo instead. Closing now.
