### ISSUE TITLE
rethrow mysql exceptions as DataJointError

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#357]
per discussion in #355 / #356, isolating client code from underlying library exception types is desirable,
and instead, code should throw DataJointError exceptions. Testing/auditing of code to this end should be performed.

**Comment by ixcat** [comment]
Thinking appropriate logic might be best pushed down into datajoint.connection.Connection.query() but am hesitant to begin altering such a low level function at this stage without some feedback.

An alternate approach would be to inventory/adapt the existing catches of mysql exceptions higher up the stack, and then once these are inventories coalesced, perform some push down into Connection.query()

Also, it seems like this might have some bearing on #279 #292 efforts, so best to avoid conflicts.

Obviously, this is what separate branches are for...

Perhaps I will begin with approach #2 in a private bugfix branch for the moment, but thoughts are welcome here..

**Comment by ixcat** [comment]
Third approach could be to simply 'chip away' at these one by one, and might be most workable, though leads to more commits..

**Comment by dimitri-yatsenko** [comment]
The argument not to push down to the query method is that the message can be customized to the attempted operation.  I would say that we should gradually replace all MySQL exception with custom DataJoint exceptions but always include the original message to ensure that no information about the exception is lost.

I don't believe that this topic deserves its own issue because it's rather general and non-specific.  Let's adopt the policy of re-raising `DataJointError` and gradually implement it.  Issues should be made for individual use cases, not a blanket issue for all cases, which cannot be verified.
