### ISSUE TITLE
Avoid or warn avoid dropping when relation has been restricted

### ISSUE THREAD

**Issue by ecobost** [datajoint/datajoint-python#372]
Something like (Segmentation() & my_key).drop() should maybe warn you about whether you want to delete rather than drop. Right now, it does the same as Segmentation().drop()

**Comment by eywalker** [comment]
Given that restriction makes no sense in `drop` and this is likely mistype for `delete`, I agree that it makes sense to throw warning or even an error.

**Comment by dimitri-yatsenko** [comment]
Yes, let's throw an error. 

Should insert throw an error when invoked on a restricted set? 

```python
(Segmentation() & my_key).insert(tuple)
```

**Comment by eywalker** [comment]
I feel that the `drop` is the only case for which I feel strongly about not allowing operation on a restricted table - because it suggests that one has mistaken `drop` for `delete` but with devastatingly different outcomes.

 For other operations, it is rather convenient to be able to just work with restricted relation even if restriction would not mean anything.

**Comment by dimitri-yatsenko** [comment]
This goes back to the topic of class methods vs instance methods. Things like `drop` refer to the class rather than to the object.  Perhaps we could make it so drop could not be called on an instance.  

We could make it so `Scan().drop()` will throw the error "Drop should be called on the class"

The correct way would be 
```python
Scan.drop()
```

**Comment by eywalker** [comment]
Given that it's a bit awkward to have a class method that'll behave differently if it's called on an instance (and since making that happen would require us to write our own `Descriptor` type - which feels like an overkill), I vote that we take the minimal action of disallowing `drop` called on a restricted table.
