### ISSUE TITLE
Should `make` replace `_make_tuples`?

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#387]
Should we gradually replace `_make_tuples` with simply `make`? 

Here are my supporting arguments:
1. The term _tuples_ comes from the relational model.   We are coming to the understanding that DataJoint is much closer aligned with the Entity-Relationship model.  In the ERM, the elements of sets are called "entities" rather than "tuples". 
2. We follow different name conventions in different languages.  For example, in MATLAB, we use camelCase and `_make_tuples` is called `makeTuples`.  In the common documentation, we have to spell both versions. 
3. The word `tuple` is overloaded since it has its own definition in Python.  `_make_tuples` always inserts what amounts to Python `dict`s rather `tuple`s.  

Making the callback simply `make` would obviate these issues.  Of course, we will keep things backward compatible to keep `_make_tuples` an acceptable name.

What do you think?

**Comment by eywalker** [comment]
Minimally speaking, I'll be supportive of making `_make_tuples` into `make_tuples` - a proper non private member with no `_` at the beginning. I also agree that it would be better for Python and MATLAB implementation to be as close to each other as possible and therefor opting for single word method name like `make` may not be a bad idea. Should we make this switch, of course, we'll keep `_make_tuples` as an alias for `make` for some extended period of time.

**Comment by dimitri-yatsenko** [comment]
At the same time, it should also be clear that `make` is never to be called directly, bypassing `populate`.  Perhaps `insert` could throw an error if it is called by a `make` that is not called from a `populate`.

**Comment by ixcat** [comment]
While I do like the simplified 'make', I also see that there will probably always be some clash in how various languages expect functions to be called.. E.g. 'DataJoint C' would be ```_make_tuples``` but 'DataJoint C++' could be ```TableName::makeTuples()```, some other things might be ```make-tuples```, etc. 

If the longer term plan is to expand into multiple languages this will either mean simplifying to some LCD which isn't exactly a native fit in any one language, or, alternatively, supporting multiple 'mappings' into the 'host language conventions'. 

It seems like what we are doing now is the latter (```_make_tuples``` is a private function following python conventions), and this proposes the former (```make``` doesn't follow host language conventions but is straightforward w/r/t the DJ model). I'm personally agnostic here - there seems to be a good case for both - and thankfully the current API is simple enough this isn't such a big decision, but it might make sense to think about this overall strategy in deciding.

Another option might be to shift the API in the ```make``` case so that the language conventions aren't a mismatch - e.g. return the desired dict/list that *should be* created, and provide a default ```_make_tuples``` which calls ```make``` and then ```insert```s the result, and a default make which returns ```None```...

This would make some things a bit less obvious (multiple insert, part tables).. not sure how best to handle that.. but food for thought I suppose..

**Comment by dimitri-yatsenko** [comment]
The idea of returning a list may lead to inefficiencies because inserting items as they are generated saves memory.  Additionally, it would not work very cleanly with part tables.

**Comment by dimitri-yatsenko** [comment]
I think I am primarily motivated by points 1 and 3 on my list.  We may no longer introduce the concept of tuples in the relational theory sense.  When we started datajoint, it was in MATLAB and the term tuple was distinct but in Python the term is already used and quite differently.

**Comment by eywalker** [comment]
Yes I'm not as motivated by point 2 that much either - I'm fine dropping the term `tuples` as we are not really making use of this term throughout. And while we do this, I much rather not make the function be Python "private" (no `_` prefix). Ultimately, I'm not overly concerned with keeping the method name identical across platforms (I'm ok with `make_tuples` in one `makeTuples` in another and `MakeTuples` in yet another) either.

**Comment by dimitri-yatsenko** [comment]
Here are the requisite changes:  https://github.com/dimitri-yatsenko/datajoint-python/commit/cf3cf0ca3279f438c3d368b7740f7d9e1f9f85fc

**Comment by ixcat** [comment]
For return type: Yes this would be simple for the insert1 case but not elsewhere.

I didn't propose a generator notion because we are striving for user friendliness to less computationally minded folks, though that would solve it: e.g.: ```yield (TableClass, {k: v, ...})``` 

Definately see that the point 2 is the more salient point w/r/t the DJ theory; my emphasizing the other parts is that I'm agnostic since 'make' doesn't really capture it either... so looking elsewhere or thinking of the bigger picture might yield a deciding factor or help create a more optimal solution..

**Comment by ixcat** [comment]
this change also breaks all documentation, fwiw.

**Comment by dimitri-yatsenko** [comment]
I think we will leave `_make_tuples` for 2-3 years but update the documentation immediately.

**Comment by eywalker** [comment]
Not that I have a better alternative name suggestion quite yet, but I'm not sure if `make` is the best name either. I'm fine dropping `tuples` but `make` alone is not obvious as to what it would do.

**Comment by dimitri-yatsenko** [comment]
DataJoint is different enough that nobody knows what anything does without a brief introduction.

**Comment by eywalker** [comment]
That's no excuse for making unintuitive names, especially considering that I'm speaking from a perspective of someone who already knows what DJ is. If we are not entirely concerned about making the method name identical, I might have preferred `make_entity` rather than something like just `make`. Anyway, I would like to take some time coming up with the good name to change to and not do it in rush.

**Comment by dimitri-yatsenko** [comment]
`make` seems fine.   `produce`? `

**Comment by eywalker** [comment]
Hmm... or may be something like `enter` or `compute`? To me `compute` sort of make sense as that's what it is doing - computing entries (entities), especially in computed tables. I just feel that `make` is a bit too vague without further specifications - in that sense I would have been fine just replacing `make_tuples` with `make_entities` but indeed that's probably too long.

**Comment by dimitri-yatsenko** [comment]
`compute` make sense.  Except we have `dj.Computed` and `dj.Imported` and `compute` suggests that it's `dj.Computed`.

**Comment by fabiansinz** [comment]
I think `compute` is too generic. And it's confusing if we don't call it `import` in `dj.Import`. What about `generate`?

**Comment by eywalker** [comment]
Yeah I agree that `compute` is too asymmetric with `dj.Imported`. I just feel that `make`, `produce`, and `generate` all seem to suggest that something will be returned. In some sense, something like `_populate` would have made sense as this is ultimately something `populate` invokes but this would not be a good name for MATLAB side.

**Comment by eywalker** [comment]
How about `fill`?

**Comment by dimitri-yatsenko** [comment]
I am still more inclined with `make` -- kind of continuous with `_make_tuples` but `compute` works too.   In steinbruch they called it `import`.  `generate` may be confused with Python generators and it suggests continual production rather than a one-time event, I think.

I think we should stick with `make`.  I don't think `make` suggests that it returns anything.

**Comment by eywalker** [comment]
After spending some more thought about this, I feel that I can be fine with either `fill` or `make`.

**Comment by dimitri-yatsenko** [comment]
Fixed this with #377
