### ISSUE TITLE
Evaluating an expression returning the schema module results in missing schema name in ERD plot

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#393]
```
vmod = dj.create_virtual_module('vmod','schema_name')
vmod
dj.ERD(vmod)
```

results in ```_.Table``` in ERD rather than ```vmod.Table```

**Comment by eywalker** [comment]
This is caused by the fact that when you just type in e.g. `vmod` in Jupyter notebook, it assigns the result to the variable `_`. When you run `dj.ERD(vmod)`, DJ searches through the context map (usually `locals()`) - list of variable names - and finds the `_` matches `vmod` before it finds the name `vmod` matches `vmod`. As a result the name `_` is used in place of `vmod` in the ERD plotting. I propose that we skip any variable that starts with `_` during the lookup process.
