### ISSUE TITLE
Improve error 1406 "Data too long .." message

### ISSUE THREAD

**Issue by Visdoom** [datajoint/datajoint-python#446]
The issue came up when being surprised about a 
```DataError: (1406, "Data too long for column 'feature' at row 1")``` 

I was not aware of the internal data compression. Thus, I was able to insert data that technically would not fit into a `blob` without any feedback of doing so. 
Later on, when trying to insert data of the same dimensions I ran into the `DataError: 1406` since the objects size could not be compressed sufficiently.

Maybe one could adjust the error message or check if the uncompressed data does not fit and throw a warning or a suggestion that this could cause problems in the long run.

**Comment by dimitri-yatsenko** [comment]
I think we should rule out throwing a warning that the data won't fit before compression because many data are well compressed and getting a warning every time may not be helpful.  I think datajoint should catch this exception and throw an additional explanation that compression was not sufficient to squeeze the data and to suggest upgrading the datatype.

**Comment by guzman-raphael** [comment]
@Visdoom Given that the error message is clear that the data is too long proceeding with closing this issue. Utilizing a `longblob` is the recommended approach.
