### ISSUE TITLE
Drop pre-Python 3.6 support

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#452]
I start this issue to keep tracking the possibility of dropping pre-3.6 support.  In Python 3.6, all dicts became ordered dicts.  This includes `kwargs` in function definitions.  I would like to drop support for Python 3.4 and Python 3.5 as soon as reasonably possible but not sooner, so I would like to know when that could be.  This issue will be used to schedule this transition.

**Comment by eywalker** [comment]
I wouldn't drop support for Python 3.5 until Python 3.6 becomes the default Python installation version for most major operating systems and Linux distributions.

**Comment by ixcat** [comment]
Personally, I don't see a big issue if this is well coordinated with users - 

on the windows side, python is always a manual install and isn't tied to the platform,
on the linux side, most distributions are still on 2.x and so any 3.x is typically the latest;
failing that things like pyenv & so on (or even manual builds) are pretty easily available.

if we wanted to be conservative & tie to distributions/platforms:

MacOS is well covered by homebrew and still ships 2.7

RHEL7 still ships 2.7; python3.6 is available in the 'EPEL' (Extra Packages for Enterprise Linux) repository

Ubuntu 14.04 (EOL Apr-2019) / 16.04 (EOL Apr-2021) might be the biggest issue, seems to provide 3.4 and 3.5 out of the box  so users would need to add a 3rd party repo & install from it. (though I'm not an expert in this area)

This could be a good time to revisit #293 (conda packaging) since that would provide a workaround for all major cases.. which apparently is tied to me, so yes...

**Comment by eywalker** [comment]
(understanding that @ixcat's comment was written before mine 🙂)
The fact that Python 3.5 is still the default for the latest Ubuntu LTS (still 16.04) is precisely my point for waiting up. Especially given that DJ is working just fine without the need for default ordered dict, I don't see any strong reason to push forward with the change to Python 3.6 unless that's pretty much the version people will get anyway. Furthermore, in general I like the idea of supporting at least the last two major releases, which will be Python 3.5 and 3.6 at the moment, so until 3.7 is out, I wouldn't want to throw support for Python 3.5.

**Comment by ixcat** [comment]
Agree I take a more aggressive approach to updating than some users might, so perhaps my 'not a big deal' is more a personal response :)

As an aside - to some extent the policy here will potentially need to grow more strict over time; we are currently given a bit more flexibility since 'system' pythons are still 2.7 in many cases - once these all shift to 3.x, it will be a 'harder sell' to require an upgrade; or alternatively, failing that, provide some 'datajoint' managed python mechanism which is 'official' for all platforms.

Another idea along the lines @eywalker proposed could be to tie to some N months/years past the oldest of the newest releases of some set of platforms. E.g. Ubuntu 18.04 will include 3.6, and potentially the next macos, so potentially N months after the last of these releases we could/would depreciate, etc.

**Comment by dimitri-yatsenko** [comment]
Agreed.  I just want to track this and plan the transition.

**Comment by mspacek** [comment]
I had no idea Python 3.6 had order preserving dictionaries. That sounds great! Unfortunately, apparently it's not a feature that should be relied upon, at least not yet:

From https://docs.python.org/3/whatsnew/3.6.html#new-dict-implementation:

> The order-preserving aspect of this new implementation is considered an implementation detail and should not be relied upon (this may change in the future, but it is desired to have this new dict implementation in the language for a few releases before changing the language spec to mandate order-preserving semantics for all current and future Python implementations; this also helps preserve backwards-compatibility with older versions of the language where random iteration order is still in effect, e.g. Python 3.5).

We're also still using Python 3.5 (via Xubuntu 16.04), and probably won't switch to Python 3.6 and Xubuntu 18.04 for another year or so.

**Comment by dimitri-yatsenko** [comment]
Ordered dicts are here to stay.  We can rely on them.  Here is some good background: https://www.youtube.com/watch?v=p33CVV29OG8

**Comment by mspacek** [comment]
Ha, so it might just be a matter of Guido getting used to it :)

**Comment by mspacek** [comment]
Just for reference, here was the official blessing by the BDFL :)

https://mail.python.org/pipermail/python-dev/2017-December/151283.html

**Comment by dimitri-yatsenko** [comment]
What's the latest on dropping support for 3.4 and 3.5?   

For example, #500 is failing on 3.4 and 3.5 due to some dict issue.

**Comment by eywalker** [comment]
We have agreed on supporting at least the most recent 3 versions of Python 3, so we must support at least 3.5 and beyond, and preferably even 3.4 unless you have a really strong reason to drop its support. So please fix the code so at least 3.5 passes.

**Comment by dimitri-yatsenko** [comment]
Ok, Python 3.8 is coming out next year.  So we will need to support 3.5 for a while.

**Comment by eywalker** [comment]
Exactly. Furthermore, most LTS Linux distro still ships with Python 3.5, so we need to support this anyway.

**Comment by dimitri-yatsenko** [comment]
Closing for now.  We resolved to support versions until they are not longer installed by default in latest releases of major operating systems.
