### ISSUE TITLE
Errors in make() cause memory leak during populate(suppress_errors=True)

### ISSUE THREAD

**Issue by mspacek** [datajoint/datajoint-python#461]
I've noticed that the memory usage of the ipython process in which we typically run datajoint can grow quite quickly during a big `populate(suppress_errors=True)` job, which continues despite the errors. Memory usage gets into the multi GB range. Eliminating the errors raised in `make()` eliminated the memory leak. I'm not sure if the memory leak is due to `suppress_errors=True`, or if that just makes it easier to notice.

Any ideas on how to create a minimal example? Is there a public test database or something? I guess all that's needed is to call `make` many times with many keys, and raise an error on each call while suppressing those errors with `populate(suppress_errors=True)`

**Comment by dimitri-yatsenko** [comment]
Do you think it's a memory leak or memory use.  `populate` will return the `error_list` containing the error stacks for each error that occurred.  This may take substantial memory.

**Comment by mspacek** [comment]
I haven't had time to test very carefully, but I don't think it has to do with the returned `error_list`. I get the same problem even when I don't bind the return value to anything. Doesn't the error list only return `Error` objects? Maybe somehow those errors are holding references to some data that was loaded during `make()`? Also, if I recall correctly, `gc.collect()` didn't do anything to free memory after `populate()` was complete. The only solution was to exit IPython.

**Comment by mspacek** [comment]
Our recent `populate(suppress_errors=True)` attempts are getting a bit ridiculous, hitting something like 15 GB of memory usage, due to an increasing number of populate errors. Even when I delete the returned `error_list` and then garbage collect multiple times, memory usage for the IPython process doesn't change.

Any ideas on how to proceed? I tried running `pympler.asizeof.asizeof()` on all the objects listed by `whos` in IPython, but that didn't reveal anything interesting. `gc.collect()` says there are 7 unreachable objects, but I doubt that's it.

Even when I disable binding of the returned errors to anything in our code, the same memory bloat still occurs. So I get the impression this is due to something internal to datajoint. Could this maybe have something to do with the atomicity of `make()` holding on to objects after a suppressed error?

**Comment by dimitri-yatsenko** [comment]
Should we provide the option not to accumulate the `error_list`?  For example, we could add the argument `return_error_list = False`.

**Comment by mspacek** [comment]
@dimitri-yatsenko Oops, I just saw your comment. OK, I'll try commenting out
```python
error_list.append((key, error))
```
in autopopulate.py, and see if that helps.

**Comment by mspacek** [comment]
Commenting out the append fixed the problem. I guess some of those error objects might be holding references to some binary data that failed to be inserted, something like that. I tried appending just the error message instead of the full error object, and the problem remained fixed, so I've made a PR for that. So far seems to be working well.

**Comment by mspacek** [comment]
Just FYI, I was getting this error occasionally during populate():
```
InternalError: (1118, 'The size of BLOB/TEXT data inserted in one transaction is greater than 10% of redo log size. Increase the redo log size using innodb_log_file_size.')
```
This was on MariaDB, which is using innodb version 2.6.36 or so. According to [this](https://bugs.mysql.com/bug.php?id=85970) post, that error caused memory leaks in mysql 2.6. Not clear if that was in the server process or the client process. I increased the log file size and the error went away. I'm not sure if it may have been contributing to the high memory usage I noticed when Exception objects were being returned.

**Comment by ixcat** [comment]
Hi - Thanks for the report.

The configuration variable `innodb_log_file_size` definitely pertains to the server-side configuration,
The error report also seems to suggest this in a roundabout way - `Watch mysql error log, and memory usage.`. (the error log specifically pertaining to the server) 

Since the previous `error_list` also copied the insert key, which likely contained large blobs in this case, and the fix cleaned things up, I agree with the changes here that this was a likely culprit.

One of our major installations is on 5.6 and haven't seen major server side leaks/memory growth; that said we have probably long since tuned up `innodb_log_file_size` for the workload so that this error is rare/nonexistent (set `=4096M`); probably a good idea to note this and be on the lookout however :)

Side note, this is a good setting to be sure to set for heavy blob use - relatedly,
our starting point for mysql when used for datajoint are available here:

https://github.com/datajoint/mysql-docker/blob/master/my.cnf

 Currently in lines 44-53.
