### ISSUE TITLE
ERD: entity relationship diagram

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#7]
This was previously implemented using the networkx module.  Make this work with the new implementation, probably as a method of Connection.

**Comment by eywalker** [comment]
I realized that automated testing of ERD can be quite difficult as its primary output is a matplotlib figure. I'm guessing we should still write test to make sure the the code runs without hanging. Is there a good way to test for plotting?

**Comment by fabiansinz** [comment]
There is a decorator that allows you to compare an image to a reference image. However, the problem is that you have to adhere to some matplotlib directory structures which we don't. Therefore, I'd propose to simply test whether the erd produces a figure. Another option would be to test whether the erd produces the correct graph and assume that plotting is correctly is tested somewhere else.

**Comment by eywalker** [comment]
I'm going to go with the latter solution where I check whether the graph structure produced via ERD commands correctly match to what's expected.

**Comment by dimitri-yatsenko** [comment]
Fixed in PR #208
