### ISSUE TITLE
inform index of failed insert when inserting muliple rows

### ISSUE THREAD

**Issue by jcouto** [datajoint/datajoint-python#747]
This is a feature request.

Often when inserting multiple rows using the .insert method it would be useful to know the index of the insert that failed.

Would it be possible to return the index along with the error message?

Thanks in advance!

**Comment by ixcat** [comment]
Agree something like this would be nice -
Unfortunately this isn't clearly available in the error from MySQL so this might be difficult to implement - one non-ideal workaround could be to catch the exception and then manually iterate with insert1 to find the offending record, conceivably this could be done in datajoint directly, but not sure if we'd want to, at least without some special flag, since it would change transaction mechanics and silently change performance between successful/unsuccessful cases.. 
Probably a good idea to have a discussion about it though

**Comment by eywalker** [comment]
Yeah while I fully agree that this would have been desirable, there is no clear way to achieve this against the MySQL backend. I'm closing this issue for now but we might revisit should we implement alternate backend support where more detailed error message hits to which row failed.
