### ISSUE TITLE
UUID datatype is not documented on the datajoint python docs

### ISSUE THREAD

**Issue by Synicix** [datajoint/datajoint-python#866]
### Problem
UUID seems to be a recent feature that was implmented but it not found under the datatype docs: https://docs.datajoint.io/python/definition/06-Datatypes.html

### Requirements
This should be documented so users know that this option even exist

### Justification
No docs, not many will knows about, no one will use it.

### Alternative Considerations
Add to the docs and keep it up to date with new roll out features, not everyone has time to dig through the code to figure this out. While most people don't really look at changelogs either.

### Related Errors
None

**Comment by guzman-raphael** [comment]
@Synicix Thanks for filing this issue; it is one we're aware of.
Our policy is that language-specific documentation issues are appropriate here, however, documentation issues that are generic or independent of client language should be raised in [datajoint-docs](https://github.com/datajoint/datajoint-docs). This issue would qualify as generic since it is about a DataJoint type. Also, it does appear to be a duplicate of datajoint/datajoint-docs#247. I would suggest to move the details you've provided here to the original and close this one as a duplicate.

**Comment by Synicix** [comment]
Cool, I wasn't aware that datajoint has a sepreate doc repo. I will copy and paste the issue over there then. Thanks a lot for the pointers!
