### ISSUE TITLE
Index key error when using fetch1('KEY')

### ISSUE THREAD

**Issue by shenshan** [datajoint/datajoint-python#876]
### Description
When using fetch1('KEY') in datajoint 0.12.8, it gives this error when using fetch1('KEY'):
![image](https://user-images.githubusercontent.com/2539832/110170128-91dea080-7dae-11eb-9052-3a27f802b212.png)

**Comment by dimitri-yatsenko** [comment]
This occurred when `dj.config['fetch_format']` was set to "`frame`" to return Pandas dataframes.  The `fetch_format` applies only to results of `fetch` not `fetch1`.  But `fetch1` calls `fetch` and did not handle the dataframe results correctly. The fix was to set `format="array"` when calling `fetch` from `fetch1`.  Fixed in #857.
